version: "3.9"

services:
  app:
    build: .
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://devuser:changeme@db:5432/devdb
    depends_on:
      - redis_db
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  redis_db:
    image: redis

volumes:
  dev-db-data:
